system:
  verbose: 2
  parallel_requests: 1

run:
  seed: 42
  generations: 1

plugins:
  target_type: agent_api_generator
  probe_spec: file_prompt_probe.FilePromptProbe
  detector_spec: auto
  buffs_include_original_prompt: true
  buff_max: 64


  generators:
    chat_api_generator:
      ChatApiGenerator:
        base_url: "http://10.40.240.103:8000"
        api_endpoint: "/api/v1/chat"
        thread_id: garak-test-thread
        use_rag: true
        top_k: 6

  probes:
    file_prompt_probe:
      FilePromptProbe:
        prompts_file: "../prompt/rag_poison_prompts.txt"

reporting:
  report_dir: "./garak_full_reports"