system:
  verbose: 2
  parallel_requests: 1

run:
  seed: 42
  generations: 1

plugins:
  target_type: frontend_chain_generator
  probe_spec: file_prompt_probe.FilePromptProbe
  detector_spec: auto
  buff_spec: lowercase.Lowercase
  buffs_include_original_prompt: true
  buff_max: 64

  generators:
    frontend_chain_generator:
      FrontendChainGenerator:
        base_url: "http://10.40.240.103:3030"
        model: "omega-llama:latest"

  probes:
    file_prompt_probe:
      FilePromptProbe:
        prompts_file: "../prompt/attack_prompts_system_prompt_targets_results_20260601_100259.txt"

reporting:
  report_dir: "./garak_full_reports"