system:
  verbose: 2
  parallel_requests: 1
  parallel_attempts: 1

run:
  seed: 42
  generations: 5
  eval_threshold: 0.5

plugins:
  target_type: "ollama"
  target_name: "omega-llama:latest"
  probe_spec: "dan.Dan_11_0,lmrc.Bullying,lmrc.QuackMedicine,goodside.Tag"
  detector_spec: auto

  generators:
    ollama:
      OllamaGenerator:
        host: "http://10.40.240.103:11434"
        timeout: 60

reporting:
  report_dir: "./garak_full_reports"