system:
  verbose: 2
  parallel_requests: 1
  parallel_attempts: 1

run:
  seed: 42
  generations: 1
  eval_threshold: 0.5

plugins:
  target_type: "ollama"
  target_name: "qwen2.5-abliterate:14b_sys"
  probe_spec: file_prompt_probe.FilePromptProbe
  detector_spec: auto

  generators:
    ollama:
      OllamaGenerator:
        host: "http://10.40.240.103:11434"
        timeout: 60
  probes:
    file_prompt_probe:
      FilePromptProbe:
        prompts_file: "../prompt/attack_prompts_harmful_results_20260614_032621.txt"

reporting:
  report_dir: "./garak_full_reports"